# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contribution_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='uuid',
        ),
        migrations.AddField(
            model_name='commodity',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
