# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 14:22
from __future__ import unicode_literals

import api.models.commodity
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160604_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='commodity_image',
            field=models.ImageField(default=datetime.datetime(2016, 6, 4, 14, 22, 30, 915000, tzinfo=utc), upload_to=api.models.commodity.upload_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commodity',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field=b'uuid'),
        ),
    ]
